const $ = id => document.getElementById(id);
const defaults = {serverUrl:'https://evisa-production.up.railway.app',portalUrl:'https://evisa.immigration.gov.ng/',username:'admin',password:'',enabled:true};
let applicants=[];
function auth(c){return 'Basic '+btoa(`${c.username||''}:${c.password||''}`)}
function norm(v){return String(v||'').trim().replace(/\/+$/,'')}
async function cfg(){return {...defaults,...await chrome.storage.local.get(defaults)}}
async function api(path, options={}){const c=await cfg();const r=await fetch(norm(c.serverUrl)+path,{...options,headers:{Authorization:auth(c),...(options.headers||{})}});const ct=r.headers.get('content-type')||'';const d=r.status===204?null:(ct.includes('application/json')?await r.json():await r.text());if(!r.ok)throw new Error(d?.error||String(d||`HTTP ${r.status}`));return d}
function status(text,kind=''){const el=$('status');el.textContent=text;el.className='status '+kind}
async function loadSettings(){const c=await cfg();['serverUrl','portalUrl','username','password'].forEach(k=>$(k).value=c[k]||'');$('enabled').checked=!!c.enabled}
async function save(){const c={serverUrl:norm($('serverUrl').value),portalUrl:$('portalUrl').value.trim(),username:$('username').value.trim(),password:$('password').value,enabled:$('enabled').checked};await chrome.storage.local.set(c);status('Saved. Testing Railway…','working');chrome.runtime.sendMessage({type:'EVISA_POPUP_TEST'},r=>{if(chrome.runtime.lastError)return status(chrome.runtime.lastError.message,'bad');status(r?.ok?'Connected to Railway. Device worker is ready.':`Connection failed: ${r?.error||'Unknown error'}`,r?.ok?'ok':'bad');refreshApplicants().catch(()=>{});});}
function applicantLabel(a){const name=[a.title,a.first_name,a.other_names,a.surname].filter(Boolean).join(' ').trim();return `${a.application_id||'No ID'}${name?' — '+name:''}`}
async function refreshApplicants(){status('Loading applicants…','working');applicants=await api('/api/applicants');const sel=$('applicant'),prev=sel.value;sel.innerHTML='<option value="">Choose applicant…</option>';for(const a of applicants){const o=document.createElement('option');o.value=a.application_id;o.textContent=applicantLabel(a);sel.appendChild(o)}if(prev&&applicants.some(a=>a.application_id===prev))sel.value=prev;updateMeta();status(`Connected. ${applicants.length} applicant(s) available.`,'ok')}
function updateMeta(){const a=applicants.find(x=>x.application_id===$('applicant').value);$('applicantMeta').textContent=a?[a.visa_category,a.nationality,a.status].filter(Boolean).join(' • '):''}
async function start(){const id=$('applicant').value;if(!id)return status('Choose an applicant first.','bad');const c=await cfg();if(!c.enabled){$('enabled').checked=true;await chrome.storage.local.set({enabled:true})}status('Checking Railway device API…','working');let health;try{health=await api('/api/health')}catch(e){throw new Error('Could not reach Railway backend: '+e.message)}if(!health?.deviceJobs){throw new Error('Railway is still running the older backend. Upload Railway Side Panel v5 to GitHub and wait for Railway to redeploy before starting automation.')}const startPage=$('startPage').value;status(`Queuing ${id}…`,'working');await api('/api/device/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({applicationIds:[id],startPage:startPage==='auto'?'auto':Number(startPage)})});chrome.runtime.sendMessage({type:'EVISA_POPUP_POLL'},r=>{if(r?.ok)status(`Automation started for ${id}. Keep this side panel open; the portal is in the main browser area.`,'working');else status(`Could not start worker: ${r?.error||'Unknown error'}`,'bad')})}
async function stop(){status('Stopping automation…','working');try{await api('/api/device/jobs/cancel',{method:'POST'});chrome.runtime.sendMessage({type:'EVISA_FORCE_STOP'},()=>status('Automation stopped.','bad'))}catch(e){status(`Stop failed: ${e.message}`,'bad')}}
async function showPortal(){status('Opening eVisa portal in the current tab…','working');chrome.runtime.sendMessage({type:'EVISA_SHOW_PORTAL_CURRENT_TAB'},r=>status(r?.ok?'eVisa portal opened in the main browser area.':'Could not open portal: '+(r?.error||'Unknown error'),r?.ok?'ok':'bad'))}
async function runtimeState(){chrome.runtime.sendMessage({type:'EVISA_GET_WORKER_STATE'},r=>{if(!r)return;const bits=[r.enabled?'Worker enabled':'Worker disabled',r.activeJob?`Running ${r.activeJob}`:'Idle'];$('workerState').textContent=bits.join(' • ')})}
$('save').onclick=()=>save().catch(e=>status(e.message,'bad'));$('refresh').onclick=()=>refreshApplicants().catch(e=>status(`Could not load applicants: ${e.message}`,'bad'));$('start').onclick=()=>start().catch(e=>status(`Start failed: ${e.message}`,'bad'));$('stop').onclick=stop;$('portal').onclick=showPortal;$('applicant').onchange=updateMeta;
chrome.runtime.onMessage.addListener(msg=>{if(msg?.type==='EVISA_SIDE_STATUS')status(msg.message||'Automation update',msg.error?'bad':'working')});
(async()=>{await loadSettings();await refreshApplicants().catch(e=>status(`Enter/save Railway credentials, then Refresh Applicants.\n${e.message}`,'bad'));await runtimeState();setInterval(runtimeState,2000)})();
